version: 2.1

jobs:
  test:
    docker:
      - image: maven:3.8-openjdk-15-slim  # Use Maven with JDK 15
    environment:
      CHROMEDRIVER_PATH: "/usr/local/bin/chromedriver"  # Set the ChromeDriver path here
    steps:
      - checkout  # Check out the code from the repository

      # Step 2: Install dependencies (unzip, curl)
      - run:
          name: Install unzip and curl
          command: |
            echo "Installing dependencies..."
            apt-get update && apt-get install -y unzip curl

      # Step 3: Install ChromeDriver using curl
      - run:
          name: Install ChromeDriver
          command: |
            echo "Downloading ChromeDriver..."
            curl -O https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            mv chromedriver /usr/local/bin/chromedriver
            chmod +x /usr/local/bin/chromedriver  # Make it executable

      # Step 4: Run tests using Maven (TestNG will generate the report)
      - run:
          name: Run Tests with TestNG
          command: mvn clean test

      # Step 5: Upload the TestNG results to Zephyr Scale using a script
      - run:
          name: Upload Test Results to Zephyr Scale
          command: |
            # TestNG results file location
            TESTNG_RESULTS_FILE="target/surefire-reports/TEST-TestSuite.xml"

            # Check if the file exists
            if [ -f "$TESTNG_RESULTS_FILE" ]; then
                echo "TestNG results found. Uploading to Zephyr Scale..."

                # Prepare the request for Zephyr Scale API (adjust for your API endpoint and credentials)
                curl -X POST "https://api.zephyrscale.smartbear.com/v2/automations/executions/junit?projectKey=SCRUM&autoCreateTestCases=true" \
                -H "Authorization: Bearer <your_zephyr_api_token>" \
                -H "Content-Type: application/xml" \
                --data-binary @target/surefire-reports/TEST-TestSuite.xml  # Upload JUnit XML results to Zephyr Scale
            else
                echo "TestNG results file not found. Skipping Zephyr upload."
            fi

workflows:
  version: 2
  test:
    jobs:
      - test
