version: 2.1

jobs:
  test:
    docker:
      - image: maven:3.8-openjdk-15-slim  # Use Maven with JDK 15
    environment:
      CHROMEDRIVER_PATH: "/usr/local/bin/chromedriver"  # Set the ChromeDriver path here
    steps:
      - checkout  # Check out the code from the repository

      # Step 2: Install dependencies (unzip, curl)
      - run:
          name: Install unzip and curl
          command: |
            echo "Installing dependencies..."
            apt-get update && apt-get install -y unzip curl

      # Step 3: Install ChromeDriver using curl
      - run:
          name: Install ChromeDriver
          command: |
            echo "Downloading ChromeDriver..."
            curl -O https://storage.googleapis.com/chrome-for-testing-public/133.0.6943.53/linux64/chromedriver-linux64.zip
            unzip chromedriver-linux64.zip
            mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
            chmod +x /usr/local/bin/chromedriver  # Make it executable

      - run:
          name: Install Maven Dependencies
          command: mvn clean install -DskipTests=true  # Install dependencies without running tests
      - run:
          name: Run Unit Tests in Surefire Format
          command: mvn test || true  # Run the tests; `|| true` ensures job doesn't fail on test failure
      - run:
          name: Upload JUnit Results to Zephyr Scale
          command: |
            # TestNG results file location
            TESTNG_RESULTS_FILE="target/surefire-reports/TEST-TestSuite.xml"

            # Check if the file exists
            if [ -f "$TESTNG_RESULTS_FILE" ]; then
                echo "TestNG results found. Uploading to Zephyr Scale..."

                # Prepare the request for Zephyr Scale API (adjust for your API endpoint and credentials)
                curl -X POST "https://api.zephyrscale.smartbear.com/v2/automations/executions/junit?projectKey=SCRUM&autoCreateTestCases=true" \
                -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb250ZXh0Ijp7ImJhc2VVcmwiOiJodHRwczovL2xvZ2ljd29ya3VzYS5hdGxhc3NpYW4ubmV0IiwidXNlciI6eyJhY2NvdW50SWQiOiI3MTIwMjA6OTMyN2U2NGItOTg5Yy00MTg4LWJhOGQtODE0ZGMwNjU4NmNkIiwidG9rZW5JZCI6ImRkYjcxM2ZhLTAyZTctNDJlMC1iYjc1LWFmMjU3ZjgwYmI3OSJ9fSwiaXNzIjoiY29tLmthbm9haC50ZXN0LW1hbmFnZXIiLCJzdWIiOiI5OTU5NDk1Yi0yZjM1LTM0NGItOWZiNC1hMzJkMmEwYTExY2MiLCJleHAiOjE3NzA1MDY5MzMsImlhdCI6MTczODk3MDkzM30.M3FZaQoYaMxUMXJOyvEhUXVE6xqw1b59uR_jlTBIORQ" \
                -H "Content-Type: application/xml" \
                --data-binary @target/surefire-reports/TEST-TestSuite.xml  # Upload JUnit XML results to Zephyr Scale
            else
                echo "TestNG results file not found. Skipping Zephyr upload."
            fi

workflows:
  version: 2
  test:
    jobs:
      - test
